### ISSUE TITLE
Fix background color / font color on fossos-website

### ISSUE THREAD

**Issue by SvenNekula** [soztag/fossos#199]
The background color and font color combination makes it unreadable (at least in chrome)
![screenshot-fossos](https://user-images.githubusercontent.com/56732386/80608925-ccadd480-8a37-11ea-80a5-b7bef0323c6b.jpg)
.

**Comment by maxheld83** [comment]
The root cause of this was a bug in an upstream package: https://github.com/rich-iannone/DiagrammeR/issues/375.

It's actually quite a convoluted bug and a couple of things made it hard to discover:

1. The current CI takes the most recent package version available. In this case, that was the updated {DiagrammeR} which shipped with the faulty `mermaid.css` which had an overly aggressive css selector which set the opacity to `0.2`, thereby rendering everything super hard to read. This problem should have been avoided (by @maxheld83) in the first place by freezing dependencies, and avoiding silent updates as per #200 (just takes time).
2. This, in turn, lead to every webpage which included a DiagrammeR plot to include the faulty CSS. Webpages (such as `/linux`) without DiagrammeR were unaffected, making this hard to debug.
3. Making this harder to debug still, my local machine had apparently cached an older version of the CSS, which rendered the website perfectly on my local machine. (This is a common feature of browser to save on bandwidth -- you can avoid it by going into incognito mode).
  This lead me to the faulty conclusion that this was browser issue, though it was actually just faulty css.
