### ISSUE TITLE
fix typo in class website cloud alternative section

### ISSUE THREAD

**Issue by Mococoa22** [soztag/fossos#52]
In the first paragraph of **Cloud Alternative** there is the sentence starting with 

> 'You will still have ~'.

 ,so the last sentence, has a grammatical mistake. 
It should have been, 

'You will still have **to** sign up to~'.

I'm sorry if it was wrong.

**Comment by Mococoa22** [comment]
You can see it from [here](https://www.maxheld.de/fossos/stack.html#operating_system_maintenance) 

I am also confused which site you mean by the class website.

**Comment by maxheld83** [comment]
thanks @Mococoa22!
You're in the right place – that's what I meant by class website: https://www.maxheld.de/fossos/

I'm going to leave this issue open, and *not* resolve this myself, just because I want to give us a chance to resolve this issue in class later when we've covered some more tools.

Thanks for spotting this!
