### ISSUE TITLE
report experience with wsl

### ISSUE THREAD

**Issue by maxheld83** [soztag/fossos#74]
starting point #70 

For future reference: Users of the WSL should be aware that their *Windows* GUIs (say, RStudio or GitHub Desktop) will always rely on the respective *Windows* CLI programs (R and git in this case). So even if you *do* install git or whatever inside the WSL (it actually ships with git), that's not the version that your windows GUIs will use.

**Comment by maxheld83** [comment]
would be nice if, after a couple of weeks of experience, someone could report on how this went, and what possible snafus might be.

**Comment by t-rop** [comment]
I've investigated the WSL a bit more and found some guides for graphical user interfaces via the WSL. 
And what should i say? It works :-) : 
![image](https://user-images.githubusercontent.com/44171964/48737471-63c10b00-ec4e-11e8-8c59-33f34fc681a2.png)
![image](https://user-images.githubusercontent.com/44171964/48737873-7daf1d80-ec4f-11e8-9723-849ef80c6e45.png)

This is the guide i followed: https://seanthegeek.net/234/graphical-linux-applications-bash-ubuntu-windows/
Afterwards, I've looked at these scripts to get some stuff like R and RStudio installed: https://askubuntu.com/questions/1032842/r-rstudio-installation-script-for-ubuntu-18-04-tdd-packages

If someone else needs help i am will do my best, just let me know either in class or via message here.

**Comment by maxheld83** [comment]
so cool! Thanks for figuring this out!

**Comment by maxheld83** [comment]
@t-rop do you have an update on this?

I vaguely remember that we kinda hit a wall in trying to get this to work before Christmas, and I came away with a sense that this wasn't perhaps a good idea, at least not when GUIs are required, because GUI support inside the WSL appeared limited.
But maybe this is changing. 

Either way, I'm going to close this, because this seemed relatively advanced, and has a real potential to confuse people even more. ("Real" Linux vm or dual-boot seems way cleaner).

Anyway, feel free to reopen if you still want to pursue this.

**Comment by t-rop** [comment]
@maxheld83 I've been investigating this topic a little further:

The WSL target group seems to be people who know Linux, but work with Windows for whatever reason, as we brainstormed at the end of a session.

[Here ](https://www.reddit.com/r/bashonubuntuonwindows/comments/ap4ixd/does_anyone_actually_recommend_wsl_over_using/egacikd) is a nice post from someone on stackoverflow. This user was working with Linux exclusively for years, but liked the Surface Hardware. With WSL, dev work can be done in Linux while hardware support for several surface features is maintained via Windows.
But it's also not "something that just comes up and works".

For a class setting where some people just know Windows, learning to use a bash / command prompt in addition to the actual topics is already quite a step. 
Combining that with requiring Linux knowledge from the get-go for doing several things 

So concluding on this, i also recommend using Linux vm / dual booting / using a native windows solution instead of WSL.

**Comment by maxheld83** [comment]
thanks @t-rop for digging some more into this!
